name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Run tests
      run: cargo test --target x86_64-pc-windows-msvc
